INSERT INTO exercises (id, name, target_body_part, movement_type, description, complexity) VALUES (1, 'test-exercise1', 'CHEST', 'COMPOUND','test-exercise-description1', 'MEDIUM');
INSERT INTO exercises (id, name, target_body_part, movement_type, description, complexity) VALUES (2, 'test-exercise2', 'ABS', 'ISOLATION','test-exercise-description2', 'EASY');
INSERT INTO exercises (id, name, target_body_part, movement_type, description, complexity) VALUES (3, 'test-exercise3', 'LEGS', 'COMPOUND','test-exercise-description3', 'MEDIUM');
INSERT INTO exercises (id, name, target_body_part, movement_type, description, complexity) VALUES (4, 'test-exercise4', 'CHEST', 'ISOLATION','test-exercise-description4', 'HARD');
INSERT INTO exercises (id, name, target_body_part, movement_type, description, complexity) VALUES (5, 'test-exercise5', 'ABS', 'COMPOUND','test-exercise-description5', 'MEDIUM');
INSERT INTO exercises (id, name, target_body_part, movement_type, description, complexity) VALUES (6, 'test-exercise6', 'LEGS', 'ISOLATION','test-exercise-description6', 'HARD');
INSERT INTO exercises (id, name, target_body_part, movement_type, description, complexity) VALUES (7, 'test-exercise7', 'BACK', 'COMPOUND','test-exercise-description7', 'EASY');
INSERT INTO exercises (id, name, target_body_part, movement_type, description, complexity) VALUES (8, 'test-exercise8', 'SHOULDERS', 'ISOLATION','test-exercise-description8', 'MEDIUM');
INSERT INTO exercises (id, name, target_body_part, movement_type, description, complexity) VALUES(9, 'test-exercise9', 'LEGS', 'COMPOUND','test-exercise-description9', 'HARD');
INSERT INTO exercises (id, name, target_body_part, movement_type, description, complexity) VALUES  (10, 'test-exercise10', 'ABDUCTORS', 'COMPOUND','test-exercise-description10', 'EASY');
